version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"  # Porta para acessar o projeto
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=cpf_db
      - DB_USERNAME=cpf_user
      - DB_PASSWORD=cpf_password
    depends_on:
      mariadb:
        condition: service_healthy
    command: ["sh", "-c", "/docker-wait-for-it.sh mariadb:3306 -t 60 -- php artisan migrate --seed"]

  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_USER=cpf_user
      - MARIADB_PASSWORD=cpf_password
      - MARIADB_DATABASE=cpf_db
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    restart: always
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
    driver: local
